server:
  port: 80

aws:
  region: ${REGION}
  accessKeyId: ${ACCESS_KEY}
  secretAccessKey: ${SECRET_KEY}
  token: ${TOKEN}

s3:
  bucketName: poc-video-original

management:
  endpoints:
    web:
      exposure:
        include: '*'
      basePath: /manage
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
